<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus/es/components/message/index'
import { ElMessageBox } from 'element-plus/es/components/message-box/index'
import api from './api'
import TextToSqlPanel from './components/TextToSqlPanel.vue'

const token = ref(localStorage.getItem('smile_admin_token'))
const login = reactive({ username: 'admin', password: 'admin123' })
// 钉钉通知只携带审批编号。即使未登录也保留深链，登录后再展示对应任务。
const deepLinkedApprovalId = Number(new URLSearchParams(window.location.search).get('approvalId')) || null
const active = ref(deepLinkedApprovalId ? 'agents' : 'dashboard')
const loading = ref(false)
const jobs = ref([]), candidates = ref([]), invitations = ref([]), providers = ref([])
const agents = ref([]), workflows = ref([]), agentRuns = ref([]), humanTasks = ref([])
const selectedCandidate = ref(1), recommendations = ref([]), activity = ref(null), report = ref(null)
const jobDialog = ref(false), candidateDialog = ref(false), inviteDialog = ref(false)
const agentRunDialog = ref(false), agentRunDrawer = ref(false), agentRunDetail = ref(null)
const jobForm = reactive({ title: '', department: '', city: '', salaryMin: 15000, salaryMax: 25000, experienceYears: 3, requiredSkills: '', description: '', status: 'PUBLISHED' })
const candidateForm = reactive({ name: '', phone: '', email: '', city: '', yearsOfExperience: 0, desiredPosition: '', skills: '', profileSummary: '' })
const inviteForm = reactive({ candidateId: 1, jobId: 1, durationMinutes: 25 })
const agentRunForm = reactive({ workflowCode: 'CANDIDATE_REPORT', candidateId: 1, jobId: 1, goal: '生成候选人与目标岗位的证据化综合报告' })

const stats = computed(() => [
  { label: '招聘中职位', value: jobs.value.filter(x => x.status === 'PUBLISHED').length, color: '#2563eb' },
  { label: '人才库候选人', value: candidates.value.length, color: '#7c3aed' },
  { label: 'AI 面试邀请', value: invitations.value.length, color: '#0891b2' },
  { label: '待处理 Agent 审批', value: humanTasks.value.length, color: '#ea580c' }
])

async function signIn() { try { const data = await api.post('/auth/login', login); localStorage.setItem('smile_admin_token', data.token); token.value = data.token; await loadAll() } catch (e) { ElMessage.error(e.message) } }
function logout() { localStorage.removeItem('smile_admin_token'); token.value = null }
async function loadAll() { loading.value = true; try { [jobs.value, candidates.value, invitations.value, providers.value, agents.value, workflows.value, agentRuns.value, humanTasks.value] = await Promise.all([api.get('/jobs'), api.get('/candidates'), api.get('/ai-interviews/invitations'), api.get('/ai/providers'), api.get('/agent-platform/agents'), api.get('/agent-platform/workflows'), api.get('/agent-platform/runs'), api.get('/agent-platform/human-tasks')]); if (candidates.value[0]) { selectedCandidate.value = candidates.value[0].id; agentRunForm.candidateId = candidates.value[0].id } if (jobs.value[0]) agentRunForm.jobId = jobs.value[0].id } catch(e) { ElMessage.error(e.message) } finally { loading.value = false } }
async function saveJob() { try { await api.post('/jobs', jobForm); jobDialog.value = false; await loadAll(); ElMessage.success('职位已创建') } catch(e) { ElMessage.error(e.message) } }
async function saveCandidate() { try { await api.post('/candidates', candidateForm); candidateDialog.value = false; await loadAll(); ElMessage.success('候选人已创建') } catch(e) { ElMessage.error(e.message) } }
async function recommend() { try { recommendations.value = await api.post(`/ai/candidates/${selectedCandidate.value}/recommend-jobs`); active.value = 'recommend'; ElMessage.success('推荐结果已生成') } catch(e) { ElMessage.error(e.message) } }
async function analyzeActivity() { try { activity.value = await api.get(`/activity/candidates/${selectedCandidate.value}/analysis`) } catch(e) { ElMessage.error(e.message) } }
async function invite() { try { await api.post('/ai-interviews/invitations', inviteForm); inviteDialog.value = false; await loadAll(); ElMessage.success('AI 面试邀请已创建') } catch(e) { ElMessage.error(e.message) } }
async function viewReport(row) { const sessionId = await ElMessageBox.prompt('请输入该邀请对应的面试 Session ID', '查看正式 AI 面试报告', { inputPattern: /^\d+$/, inputErrorMessage: '请输入数字' }).catch(() => null); if (!sessionId) return; try { report.value = await api.get(`/ai-interviews/sessions/${sessionId.value}/report`) } catch(e) { ElMessage.error(e.message) } }
async function startAgentRun() { try { const data = await api.post('/agent-platform/runs', { workflowCode: agentRunForm.workflowCode, businessType: 'CANDIDATE_JOB', businessId: `${agentRunForm.candidateId}:${agentRunForm.jobId}`, input: { candidateId: agentRunForm.candidateId, jobId: agentRunForm.jobId, goal: agentRunForm.goal } }); agentRunDialog.value = false; agentRunDetail.value = data; agentRunDrawer.value = true; await loadAgentRuntime(); ElMessage.success(data.status === 'WAITING_HUMAN' ? 'Agent 已完成自动节点，等待人工审核' : '工作流已完成') } catch(e) { ElMessage.error(e.message) } }
async function loadAgentRuntime() { [agentRuns.value, humanTasks.value] = await Promise.all([api.get('/agent-platform/runs'), api.get('/agent-platform/human-tasks')]) }
async function viewAgentRun(row) { try { agentRunDetail.value = await api.get(`/agent-platform/runs/${row.id}`); agentRunDrawer.value = true } catch(e) { ElMessage.error(e.message) } }
async function decideAgentTask(row, decision) { const action = decision === 'APPROVE' ? '批准并执行' : '拒绝'; const result = await ElMessageBox.prompt(`请输入${action}说明`, '人工审批', { inputType: 'textarea', confirmButtonText: action }).catch(() => null); if (!result) return; try { if (row.approval_type === 'TEXT_TO_SQL') { await api.post(`/text-to-sql/queries/${row.sql_query_run_id}/decisions`, { decision, comment: result.value }) } else { agentRunDetail.value = await api.post(`/agent-platform/human-tasks/${row.task_id}/decisions`, { decision, comment: result.value }); agentRunDrawer.value = true } await loadAgentRuntime(); ElMessage.success(`已${action}`) } catch(e) { ElMessage.error(e.message) } }
function tagType(status) { return ({ COMPLETED: 'success', SUCCEEDED: 'success', PUBLISHED: 'success', WAITING_HUMAN: 'warning', PENDING: 'warning', FAILED: 'danger', CANCELLED: 'info', DRAFT: 'info' })[status] || '' }
onMounted(() => token.value && loadAll())
</script>

<template>
  <div v-if="!token" class="login-page">
    <div class="brand-panel"><div class="brand-mark">S</div><h1>SmileBoss AI</h1><p>让每一次招聘决策都有证据、有温度、可复核。</p><div class="feature-line"><span>简历智能解析</span><span>人岗精准匹配</span><span>标准化 AI 初面</span></div></div>
    <el-card class="login-card" shadow="never"><h2>招聘团队登录</h2><p class="muted">欢迎回来，请登录管理工作台</p><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="login.username" size="large" /></el-form-item><el-form-item label="密码"><el-input v-model="login.password" type="password" size="large" show-password @keyup.enter="signIn" /></el-form-item><el-button type="primary" size="large" class="full" @click="signIn">登录工作台</el-button></el-form><div class="demo-tip">演示账号：admin / admin123</div></el-card>
  </div>
  <div v-else class="shell" v-loading="loading">
    <aside><div class="logo"><div class="brand-mark small">S</div><div><b>SmileBoss</b><small>AI 招聘系统</small></div></div><nav>
      <button v-for="item in [{k:'dashboard',n:'工作台'},{k:'jobs',n:'职位管理'},{k:'candidates',n:'候选人'},{k:'recommend',n:'AI 岗位推荐'},{k:'interviews',n:'AI 正式面试'},{k:'agents',n:'Agent 协作平台'},{k:'sql',n:'智能问数'},{k:'models',n:'模型状态'}]" :key="item.k" :class="{active:active===item.k}" @click="active=item.k">{{ item.n }}</button>
    </nav><button class="logout" @click="logout">退出登录</button></aside>
    <main><header><div><span class="eyebrow">RECRUITMENT INTELLIGENCE</span><h1>{{ ({dashboard:'招聘工作台',jobs:'职位管理',candidates:'候选人管理',recommend:'AI 岗位推荐',interviews:'正式 AI 面试',agents:'多 Agent 协作平台',sql:'智能问数与数据审核',models:'模型与基础设施'})[active] }}</h1></div><div class="header-actions"><el-select v-model="selectedCandidate" placeholder="选择候选人"><el-option v-for="c in candidates" :key="c.id" :label="c.name" :value="c.id" /></el-select><div class="avatar">HR</div></div></header>
      <section v-if="active==='dashboard'"><div class="stats"><div v-for="s in stats" :key="s.label" class="stat"><i :style="{background:s.color}"></i><span>{{s.label}}</span><strong>{{s.value}}</strong></div></div><div class="grid two"><div class="panel"><div class="panel-head"><div><h3>今日智能招聘</h3><p>从数据到行动的快捷入口</p></div></div><div class="quick"><button @click="jobDialog=true"><b>＋</b>创建职位<small>定义岗位与能力模型</small></button><button @click="candidateDialog=true"><b>↑</b>录入候选人<small>上传并解析候选资料</small></button><button @click="recommend"><b>✦</b>生成岗位推荐<small>规则评分与 AI 解释</small></button><button @click="inviteDialog=true"><b>◎</b>发起 AI 初面<small>标准问题与证据报告</small></button></div></div><div class="panel"><div class="panel-head"><div><h3>候选人活跃洞察</h3><p>活跃分不参与能力评分</p></div><el-button @click="analyzeActivity">立即分析</el-button></div><div v-if="activity" class="activity"><div class="score-ring"><b>{{activity.score}}</b><span>活跃分</span></div><div><el-tag>{{activity.level}}</el-tag><p>近 30 天记录 {{activity.eventCount}} 个有效行为</p><ul><li v-for="x in activity.recommendedActions" :key="x">{{x}}</li></ul></div></div><div v-else class="empty">选择候选人后生成活跃度分析</div></div></div></section>
      <section v-if="active==='jobs'" class="panel"><div class="panel-head"><div><h3>职位列表</h3><p>岗位标准是 AI 匹配和面试的唯一依据</p></div><el-button type="primary" @click="jobDialog=true">新建职位</el-button></div><el-table :data="jobs"><el-table-column prop="title" label="职位" min-width="180"/><el-table-column prop="department" label="部门"/><el-table-column prop="city" label="城市"/><el-table-column label="薪资"><template #default="s">{{s.row.salary_min}}–{{s.row.salary_max}}</template></el-table-column><el-table-column prop="required_skills" label="核心技能" min-width="260" show-overflow-tooltip/><el-table-column prop="status" label="状态"><template #default="s"><el-tag type="success">{{s.row.status}}</el-tag></template></el-table-column></el-table></section>
      <section v-if="active==='candidates'" class="panel"><div class="panel-head"><div><h3>候选人人才库</h3><p>敏感信息在正式环境应按权限脱敏</p></div><el-button type="primary" @click="candidateDialog=true">新增候选人</el-button></div><el-table :data="candidates"><el-table-column prop="name" label="姓名"/><el-table-column prop="city" label="城市"/><el-table-column prop="years_of_experience" label="经验（年）"/><el-table-column prop="desired_position" label="求职意向"/><el-table-column prop="skills" label="技能" min-width="280"/><el-table-column label="AI 操作"><template #default="s"><el-button link type="primary" @click="selectedCandidate=s.row.id;recommend()">岗位推荐</el-button></template></el-table-column></el-table></section>
      <section v-if="active==='recommend'" class="panel"><div class="panel-head"><div><h3>岗位推荐结果</h3><p>确定性规则评分；模型负责解释，不会自动淘汰</p></div><el-button type="primary" @click="recommend">重新计算</el-button></div><div v-if="recommendations.length" class="recommend-list"><article v-for="r in recommendations" :key="r.jobId"><div class="match-score" :class="r.level.toLowerCase()">{{r.score}}<small>匹配分</small></div><div class="match-body"><div><h3>{{r.jobTitle}}</h3><span>{{r.city}}</span></div><p>{{r.reason}}</p><div class="tags"><el-tag v-for="x in r.matchedSkills" :key="x" type="success">匹配 {{x}}</el-tag><el-tag v-for="x in r.missingSkills" :key="x" type="warning">待核实 {{x}}</el-tag></div></div></article></div><div v-else class="empty">点击“重新计算”生成推荐结果</div></section>
      <section v-if="active==='interviews'" class="panel"><div class="panel-head"><div><h3>正式 AI 面试</h3><p>AI 报告必须由 HR 查看原始回答后审核</p></div><el-button type="primary" @click="inviteDialog=true">发起邀请</el-button></div><el-table :data="invitations"><el-table-column prop="candidate_name" label="候选人"/><el-table-column prop="job_title" label="职位"/><el-table-column prop="title" label="面试"/><el-table-column prop="duration_minutes" label="时长（分钟）"/><el-table-column prop="status" label="状态"><template #default="s"><el-tag>{{s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="s"><el-button link @click="viewReport(s.row)">查看报告</el-button></template></el-table-column></el-table><pre v-if="report" class="json-report">{{JSON.stringify(report,null,2)}}</pre></section>
      <section v-if="active==='agents'" class="agent-console">
        <div class="stats agent-stats"><div class="stat"><i style="background:#4f46e5"></i><span>已注册 Agent</span><strong>{{agents.length}}</strong></div><div class="stat"><i style="background:#0891b2"></i><span>工作流</span><strong>{{workflows.length}}</strong></div><div class="stat"><i style="background:#059669"></i><span>已完成运行</span><strong>{{agentRuns.filter(x=>x.status==='COMPLETED').length}}</strong></div><div class="stat"><i style="background:#ea580c"></i><span>待人工审批</span><strong>{{humanTasks.length}}</strong></div></div>
        <div class="panel agent-hero"><div><span class="eyebrow">SMILEAGENT RUNTIME</span><h2>强状态工作流，不是 Agent 群聊</h2><p>每个节点都有输入、Artifact、预算、事件和检查点；Agent 只产生建议，正式结果由人工审核。</p></div><el-button type="primary" size="large" @click="agentRunDialog=true">运行候选报告工作流</el-button></div>
        <div class="grid two agent-grid"><div class="panel"><div class="panel-head"><div><h3>工作流</h3><p>发布版本及执行入口</p></div></div><div class="workflow-cards"><article v-for="w in workflows" :key="w.workflow_code"><div><b>{{w.name}}</b><small>{{w.workflow_code}} · v{{w.current_version}}</small></div><el-tag :type="tagType(w.status)">{{w.status}}</el-tag></article></div></div><div class="panel"><div class="panel-head"><div><h3>待人工审批</h3><p>人工决定会形成不可变 Artifact</p></div></div><div v-if="humanTasks.length" class="approval-list"><article v-for="t in humanTasks" :key="t.id" :class="{'deep-linked-approval': t.id === deepLinkedApprovalId}"><div><b>{{t.title}}</b><small>{{t.workflow_code}} · Run #{{t.run_id}} · 审批 #{{t.id}}</small><p>{{t.instruction}}</p></div><div><el-button size="small" @click="decideAgentTask(t,'REJECT')">拒绝</el-button><el-button size="small" type="primary" @click="decideAgentTask(t,'APPROVE')">批准</el-button></div></article></div><div v-else class="empty compact">当前没有待审批任务</div></div></div>
        <div class="panel"><div class="panel-head"><div><h3>Agent 注册表</h3><p>职责、模型策略与工具边界均版本化</p></div></div><el-table :data="agents"><el-table-column prop="name" label="Agent" min-width="180"/><el-table-column prop="agent_code" label="编码" min-width="210"/><el-table-column prop="model_policy" label="模型策略" min-width="180"/><el-table-column prop="max_model_calls" label="最大调用" width="100"/><el-table-column prop="timeout_seconds" label="超时（秒）" width="110"/><el-table-column prop="status" label="状态" width="110"><template #default="s"><el-tag :type="tagType(s.row.status)">{{s.row.status}}</el-tag></template></el-table-column></el-table></div>
        <div class="panel"><div class="panel-head"><div><h3>运行记录</h3><p>查看节点任务、Artifact、Event 与人工决定</p></div><el-button @click="loadAgentRuntime">刷新</el-button></div><el-table :data="agentRuns"><el-table-column prop="id" label="Run ID" width="90"/><el-table-column prop="workflow_code" label="工作流" min-width="180"/><el-table-column prop="business_id" label="业务对象"/><el-table-column prop="trace_id" label="Trace" min-width="240" show-overflow-tooltip/><el-table-column prop="state_version" label="状态版本" width="100"/><el-table-column prop="status" label="状态" width="150"><template #default="s"><el-tag :type="tagType(s.row.status)">{{s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="viewAgentRun(s.row)">查看轨迹</el-button></template></el-table-column></el-table></div>
      </section>
      <section v-if="active==='sql'"><TextToSqlPanel /></section>
      <section v-if="active==='models'" class="grid models"><div v-for="p in providers" :key="p.name" class="panel model"><div class="model-icon">AI</div><div><h3>{{p.name}}</h3><p>{{p.model}}</p></div><el-tag :type="p.ready?'success':'info'">{{p.ready?'已就绪':'等待密钥'}}</el-tag></div><div class="panel infra"><h3>数据基础设施</h3><p>MySQL/MariaDB · Redis · Qdrant 1024 维</p><small>开发模式当前使用 H2；切换 mysql Profile 后使用参考项目同一服务器。</small></div></section>
    </main>
    <el-dialog v-model="jobDialog" title="创建职位" width="640"><el-form label-position="top"><div class="form-grid"><el-form-item label="职位名称"><el-input v-model="jobForm.title"/></el-form-item><el-form-item label="部门"><el-input v-model="jobForm.department"/></el-form-item><el-form-item label="城市"><el-input v-model="jobForm.city"/></el-form-item><el-form-item label="工作经验"><el-input-number v-model="jobForm.experienceYears"/></el-form-item></div><el-form-item label="核心技能（逗号分隔）"><el-input v-model="jobForm.requiredSkills"/></el-form-item><el-form-item label="职位描述"><el-input v-model="jobForm.description" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="jobDialog=false">取消</el-button><el-button type="primary" @click="saveJob">创建</el-button></template></el-dialog>
    <el-dialog v-model="candidateDialog" title="新增候选人" width="640"><el-form label-position="top"><div class="form-grid"><el-form-item label="姓名"><el-input v-model="candidateForm.name"/></el-form-item><el-form-item label="城市"><el-input v-model="candidateForm.city"/></el-form-item><el-form-item label="手机号"><el-input v-model="candidateForm.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="candidateForm.email"/></el-form-item><el-form-item label="工作经验"><el-input-number v-model="candidateForm.yearsOfExperience"/></el-form-item><el-form-item label="求职意向"><el-input v-model="candidateForm.desiredPosition"/></el-form-item></div><el-form-item label="技能"><el-input v-model="candidateForm.skills"/></el-form-item><el-form-item label="个人摘要"><el-input v-model="candidateForm.profileSummary" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="candidateDialog=false">取消</el-button><el-button type="primary" @click="saveCandidate">保存</el-button></template></el-dialog>
    <el-dialog v-model="inviteDialog" title="发起正式 AI 面试" width="520"><el-form label-position="top"><el-form-item label="候选人"><el-select v-model="inviteForm.candidateId" class="full"><el-option v-for="c in candidates" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="职位"><el-select v-model="inviteForm.jobId" class="full"><el-option v-for="j in jobs" :key="j.id" :label="j.title" :value="j.id"/></el-select></el-form-item><el-form-item label="面试时长"><el-input-number v-model="inviteForm.durationMinutes" :min="10" :max="60"/> 分钟</el-form-item><el-alert title="AI 面试不会自动淘汰候选人，报告生成后需要 HR 人工审核。" type="info" :closable="false"/></el-form><template #footer><el-button @click="inviteDialog=false">取消</el-button><el-button type="primary" @click="invite">发送邀请</el-button></template></el-dialog>
    <el-dialog v-model="agentRunDialog" title="运行候选人综合报告工作流" width="620"><el-form label-position="top"><el-form-item label="工作流"><el-select v-model="agentRunForm.workflowCode" class="full"><el-option v-for="w in workflows.filter(x=>x.status==='PUBLISHED')" :key="w.workflow_code" :label="`${w.name} · v${w.current_version}`" :value="w.workflow_code"/></el-select></el-form-item><div class="form-grid"><el-form-item label="候选人"><el-select v-model="agentRunForm.candidateId" class="full"><el-option v-for="c in candidates" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="目标岗位"><el-select v-model="agentRunForm.jobId" class="full"><el-option v-for="j in jobs" :key="j.id" :label="j.title" :value="j.id"/></el-select></el-form-item></div><el-form-item label="任务目标"><el-input v-model="agentRunForm.goal" type="textarea" :rows="3"/></el-form-item><el-alert title="工作流会在合规审计后暂停，等待 HR 人工批准或拒绝。" type="info" :closable="false"/></el-form><template #footer><el-button @click="agentRunDialog=false">取消</el-button><el-button type="primary" @click="startAgentRun">开始运行</el-button></template></el-dialog>
    <el-drawer v-model="agentRunDrawer" title="Agent 运行轨迹" size="58%"><template v-if="agentRunDetail"><div class="run-summary"><el-tag :type="tagType(agentRunDetail.status)" size="large">{{agentRunDetail.status}}</el-tag><b>Run #{{agentRunDetail.id}}</b><span>状态版本 {{agentRunDetail.state_version}}</span><span>Trace {{agentRunDetail.trace_id}}</span></div><h3>节点任务</h3><el-timeline><el-timeline-item v-for="t in agentRunDetail.tasks" :key="t.id" :type="t.status==='SUCCEEDED'?'success':t.status==='FAILED'?'danger':'warning'" :timestamp="t.node_type"><b>{{t.node_code}}</b><el-tag class="task-tag" size="small" :type="tagType(t.status)">{{t.status}}</el-tag><small v-if="t.agent_code">{{t.agent_code}} · v{{t.agent_version}}</small></el-timeline-item></el-timeline><h3>Artifacts</h3><el-collapse><el-collapse-item v-for="a in agentRunDetail.artifacts" :key="a.id" :title="`#${a.id} · ${a.artifact_type} · ${a.producer_code}`"><pre class="artifact-json">{{JSON.stringify(a.content_json,null,2)}}</pre></el-collapse-item></el-collapse><h3>Events</h3><el-table :data="agentRunDetail.events" size="small"><el-table-column prop="id" label="#" width="60"/><el-table-column prop="event_type" label="事件" min-width="210"/><el-table-column prop="node_code" label="节点" min-width="160"/><el-table-column prop="created_at" label="时间" min-width="180"/></el-table></template></el-drawer>
  </div>
</template>
