<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus/es/components/message/index'
import api from './api'
const token=ref(localStorage.getItem('smile_candidate_token')),active=ref('home'),jobs=ref([]),recommendations=ref([]),invitations=ref([])
const login=reactive({username:'candidate',password:'demo123'}),resumeText=ref(''),resumeResult=ref(null),candidateId=ref(1)
const mock=reactive({sessionId:null,question:'',answer:'',round:0,report:null}),official=reactive({sessionId:null,question:'',answer:'',round:0,done:false})
async function signIn(){try{const d=await api.post('/auth/login',login);localStorage.setItem('smile_candidate_token',d.token);token.value=d.token;await load()}catch(e){ElMessage.error(e.message)}}
async function load(){try{jobs.value=await api.get('/jobs?status=PUBLISHED');invitations.value=await api.get(`/ai-interviews/invitations?candidateId=${candidateId.value}`)}catch(e){ElMessage.error(e.message)}}
async function parse(){try{resumeResult.value=await api.post('/resumes/parse-text',{candidateId:candidateId.value,text:resumeText.value});ElMessage.success('简历解析完成');active.value='resume'}catch(e){ElMessage.error(e.message)}}
async function upload(e){const file=e.target.files[0];if(!file)return;const form=new FormData();form.append('file',file);try{resumeResult.value=await api.post(`/resumes/upload?candidateId=${candidateId.value}`,form);ElMessage.success('简历解析完成')}catch(err){ElMessage.error(err.message)}}
async function recommend(){try{recommendations.value=await api.post(`/ai/candidates/${candidateId.value}/recommend-jobs`);active.value='jobs'}catch(e){ElMessage.error(e.message)}}
async function startMock(jobId=1){try{const d=await api.post('/mock-interviews',{candidateId:candidateId.value,jobId,type:'TECHNICAL'});Object.assign(mock,{sessionId:d.sessionId,question:d.question,round:d.round,answer:'',report:null});active.value='mock'}catch(e){ElMessage.error(e.message)}}
async function answerMock(){try{const d=await api.post(`/mock-interviews/${mock.sessionId}/answers`,{answer:mock.answer});mock.answer='';if(d.action==='FINISH'){mock.report=d.report;mock.question=''}else{mock.question=d.question;mock.round=d.round}}catch(e){ElMessage.error(e.message)}}
async function startOfficial(inv){try{const d=await api.post(`/ai-interviews/invitations/${inv.id}/start`,{consent:true});Object.assign(official,{sessionId:d.sessionId,question:d.question,round:d.round,answer:'',done:false});active.value='official'}catch(e){ElMessage.error(e.message)}}
async function answerOfficial(){try{const d=await api.post(`/ai-interviews/sessions/${official.sessionId}/answers`,{answer:official.answer});official.answer='';if(d.action==='FINISH'){official.done=true;official.question='';await load()}else{official.question=d.question;official.round=d.round}}catch(e){ElMessage.error(e.message)}}
function logout(){localStorage.removeItem('smile_candidate_token');token.value=null}onMounted(()=>token.value&&load())
</script>
<template>
<div v-if="!token" class="login"><div class="login-copy"><div class="logo">S</div><span>SmileBoss AI</span><h1>找到真正适合你的工作</h1><p>完善简历、发现机会、练习面试。每一项 AI 建议都有明确依据，最终选择始终属于你。</p></div><el-card class="login-box"><h2>候选人登录</h2><p>继续你的求职旅程</p><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="login.username" size="large"/></el-form-item><el-form-item label="密码"><el-input v-model="login.password" type="password" show-password size="large" @keyup.enter="signIn"/></el-form-item><el-button type="primary" size="large" @click="signIn">登录</el-button></el-form><small>演示账号 candidate / demo123</small></el-card></div>
<div v-else><header><div class="wordmark"><div class="logo mini">S</div><b>SmileBoss</b></div><nav><button v-for="i in [{k:'home',n:'首页'},{k:'resume',n:'我的简历'},{k:'jobs',n:'岗位推荐'},{k:'mock',n:'模拟面试'},{k:'official',n:'AI 面试'}]" :class="{active:active===i.k}" @click="active=i.k">{{i.n}}</button></nav><button class="exit" @click="logout">退出</button></header>
<main>
 <section v-if="active==='home'" class="hero"><div><span class="pill">AI CAREER COPILOT</span><h1>让好机会，<br><em>看见真实的你。</em></h1><p>从简历完整度到岗位匹配，从模拟练习到企业 AI 初面，我们帮你准备得更从容。</p><div class="hero-actions"><el-button type="primary" size="large" @click="active='resume'">完善我的简历</el-button><el-button size="large" @click="recommend">查看岗位推荐</el-button></div></div><div class="hero-card"><div class="orbit one">简历解析</div><div class="orbit two">岗位匹配</div><div class="orbit three">面试练习</div><div class="core"><b>AI</b><span>求职助手</span></div></div></section>
 <section v-if="active==='home'" class="feature-grid"><article><span>01</span><h3>简历智能体检</h3><p>自动识别经历、技能和项目，给出明确的完整度改进建议。</p></article><article><span>02</span><h3>适合你的岗位</h3><p>技能、经验、城市与求职意向多维匹配，清楚展示差距。</p></article><article><span>03</span><h3>更真实的面试练习</h3><p>结合目标岗位动态提问，完成后获得证据化反馈报告。</p></article></section>
 <section v-if="active==='resume'" class="page"><div class="title"><span>RESUME INTELLIGENCE</span><h1>我的简历</h1><p>支持 PDF、DOCX、TXT，也可以直接粘贴简历文本。</p></div><div class="split"><div class="card"><h3>上传简历文件</h3><label class="upload"><input type="file" accept=".pdf,.doc,.docx,.txt,.md" @change="upload"><b>↑</b><span>点击选择简历文件</span><small>文件最大 20MB；扫描件暂需 OCR</small></label><div class="or">或者粘贴简历文本</div><el-input v-model="resumeText" type="textarea" :rows="10" placeholder="粘贴包含工作经历、项目经历、技能和教育经历的简历内容……"/><el-button type="primary" class="wide" @click="parse">开始智能解析</el-button></div><div class="card result"><template v-if="resumeResult"><div class="complete"><div><strong>{{resumeResult.completeness.score}}</strong><span>完整度</span></div><h3>{{resumeResult.completeness.level}}</h3></div><h3>已识别技能</h3><div class="tags"><el-tag v-for="s in resumeResult.structured.skills" :key="s">{{s}}</el-tag></div><h3>优化建议</h3><ul><li v-for="x in resumeResult.completeness.issues" :key="x.title"><b>{{x.title}}</b><span>{{x.suggestion}}</span></li></ul></template><div v-else class="placeholder">解析结果和完整度建议会显示在这里</div></div></div></section>
 <section v-if="active==='jobs'" class="page"><div class="title inline"><div><span>JOB MATCHING</span><h1>为你推荐的岗位</h1><p>匹配分和账号活跃度完全分开，活跃度不会降低你的能力评价。</p></div><el-button type="primary" @click="recommend">重新匹配</el-button></div><div class="jobs"><article v-for="j in (recommendations.length?recommendations:jobs)" :key="j.jobId||j.id"><div class="job-top"><div><small>{{j.city}}</small><h2>{{j.jobTitle||j.title}}</h2></div><div v-if="j.score" class="score">{{j.score}}<small>匹配分</small></div></div><p>{{j.reason||j.description}}</p><div class="tags"><el-tag v-for="s in (j.matchedSkills||String(j.required_skills||'').split(','))" :key="s" type="success">{{s}}</el-tag><el-tag v-for="s in j.missingSkills" :key="s" type="warning">待核实 {{s}}</el-tag></div><div class="job-actions"><el-button @click="startMock(j.jobId||j.id)">先模拟面试</el-button><el-button type="primary">查看职位</el-button></div></article></div></section>
 <section v-if="active==='mock'" class="page interview-page"><div class="title"><span>PRACTICE INTERVIEW</span><h1>AI 模拟面试</h1><p>练习结果归你本人，不会自动提供给招聘企业。</p></div><div v-if="!mock.sessionId" class="start-card"><div class="mic">✦</div><h2>准备好开始一次 5 题模拟面试了吗？</h2><p>建议预留 15 分钟，用 STAR 结构回答并尽量提供真实数据。</p><el-button type="primary" size="large" @click="startMock(1)">开始模拟面试</el-button></div><div v-else-if="!mock.report" class="chat-card"><div class="progress"><span>问题 {{mock.round}} / 5</span><el-progress :percentage="mock.round*20" :show-text="false"/></div><div class="ai-question"><div class="ai-avatar">AI</div><p>{{mock.question}}</p></div><el-input v-model="mock.answer" type="textarea" :rows="8" placeholder="输入你的回答，建议包括背景、任务、行动和结果……"/><el-button type="primary" size="large" :disabled="!mock.answer.trim()" @click="answerMock">提交回答</el-button></div><div v-else class="report-card"><div class="report-score"><strong>{{mock.report.score}}</strong><span>{{mock.report.level}}</span></div><h2>模拟面试完成</h2><p>{{mock.report.notice}}</p><h3>下一步练习建议</h3><ul><li v-for="x in mock.report.improvements" :key="x">{{x}}</li></ul><el-button @click="mock.sessionId=null;mock.report=null">再练一次</el-button></div></section>
 <section v-if="active==='official'" class="page interview-page"><div class="title"><span>OFFICIAL AI INTERVIEW</span><h1>企业 AI 初面</h1><p>正式面试结果只作招聘辅助，并由企业招聘人员人工审核。</p></div><div v-if="!official.sessionId" class="invites"><article v-for="i in invitations" :key="i.id"><div><el-tag>{{i.status}}</el-tag><h2>{{i.job_title}}</h2><p>{{i.title}} · {{i.duration_minutes}} 分钟</p></div><el-button v-if="i.status==='INVITED'" type="primary" @click="startOfficial(i)">阅读授权并开始</el-button></article><div v-if="!invitations.length" class="placeholder">当前没有 AI 面试邀请</div></div><div v-else-if="!official.done" class="chat-card official"><el-alert title="这是一场正式 AI 初面。请基于真实经历回答；系统不会通过表情、声音或敏感属性评价你。" type="info" :closable="false"/><div class="progress"><span>正式问题 {{official.round}} / 6</span><el-progress :percentage="official.round*100/6" :show-text="false"/></div><div class="ai-question"><div class="ai-avatar">AI</div><p>{{official.question}}</p></div><el-input v-model="official.answer" type="textarea" :rows="8"/><el-button type="primary" size="large" :disabled="!official.answer.trim()" @click="answerOfficial">提交并继续</el-button></div><div v-else class="report-card"><div class="done">✓</div><h2>面试已提交</h2><p>感谢你的认真回答。AI 正在整理带证据的辅助报告，企业招聘人员审核后会更新招聘进度。</p><el-button @click="official.sessionId=null;load()">返回邀请列表</el-button></div></section>
</main><footer>SmileBoss AI · AI 辅助招聘，不替代人的最终判断</footer></div>
</template>
